== LOMBARDIA

In termini geografici, la Lombardia non si può considerare un territorio 
unitario, nel senso di territorio delimitato da precise conformazioni 
fisiche, sia per la varietà di paesaggi che l'attraversano senza racchiu
derla, sia perché i confini amministrativi, molto spesso, sono il frutto 
di complesse vicende storiche. Tuttavia è possibile delineare a grandi l
inee il suo territorio amministrativo attraverso rilievi, laghi e fiumi. 
A delimitare la Lombardia a nord si può adoperare lo spartiacque alpino 
tra la Valtellina e le valli del Reno e dell'Inn anche se, a volte, il c
onfine oltrepassa il versante valtellinese. A est sono il lago di Garda e
il fiume Mincio a separare la Lombardia da altre regioni italiane; così c
d il Po (eccezion fatta per l'Oltrepò pavese e l'Oltrepò mantovano che s
i estendono più a sud), e a ovest il Lago Maggiore e il Ticino (con l'eccez
ione della Lomellina che sconfina verso il Piemonte) possono servire da d
istinguere la Lombardia dalle altre regioni. Questi confini racchiudono u
n territorio di circa 23.861 km²,[13] rendendola la quarta regione italia
na per estensione superficiale. In un viaggio attraverso la regione, da n
ord verso sud, s'incontrano lungo il cammino per primi i rilievi delle Al
pi, poco più a sud le Prealpi seguite da dolci colline che smussano il pas
saggio dalla montagna alla Pianura Padana. Proprio lungo la fascia prealp
ina si trovano alcuni dei più grandi laghi d'Italia (come il lago di Gard
In termini geografici, la Lombardia non si può considerare un territorio 
unitario, nel senso di territorio delimitato da precise conformazioni 
fisiche, sia per la varietà di paesaggi che l'attraversano senza racchiu
derla, sia perché i confini amministrativi, molto spesso, sono il frutto 
di complesse vicende storiche. Tuttavia è possibile delineare a grandi l
inee il suo territorio amministrativo attraverso rilievi, laghi e fiumi. 
A delimitare la Lombardia a nord si può adoperare lo spartiacque alpino 
tra la Valtellina e le valli del Reno e dell'Inn anche se, a volte, il c
onfine oltrepassa il versante valtellinese. A est sono il lago di Garda e
il fiume Mincio a separare la Lombardia da altre regioni italiane; così c
d il Po (eccezion fatta per l'Oltrepò pavese e l'Oltrepò mantovano che s
i estendono più a sud), e a ovest il Lago Maggiore e il Ticino (con l'eccez
ione della Lomellina che sconfina verso il Piemonte) possono servire da d
istinguere la Lombardia dalle altre regioni. Questi confini racchiudono u
n territorio di circa 23.861 km²,[13] rendendola la quarta regione italia
na per estensione superficiale. In un viaggio attraverso la regione, da n
ord verso sud, s'incontrano lungo il cammino per primi i rilievi delle Al
pi, poco più a sud le Prealpi seguite da dolci colline che smussano il pas
saggio dalla montagna alla Pianura Padana. Proprio lungo la fascia prealp
ina si trovano alcuni dei più grandi laghi d'Italia (come il lago di Gard
